name: diagnostics_dart
description: "A Flutter web application for monitoring and displaying Azure Portal Extension diagnostics across different environments."
version: 1.0.0+1
license: MIT
repository: https://github.com/joechung2008/diagnostics-dart
publish_to: none
environment:
  sdk: '>=3.9.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
flutter:
  uses-material-design: true
